partitions:
  - name: default
    queues:
      - name: root
        limits:
          - limit:
            users:
            - john
            - sue
            maxapplications: 10
            maxresources: {memory: 10000, vcore: 10}
          - limit:
            users:
            - bob
            maxapplications: 100
        queues:
          - name: level1
            limits:
              - limit:
                users:
                - user@domain
                - testuser
                maxapplications: 10
              - limit:
                groups:
                - "*"
                maxapplications: 10
              - limit:
                groups:
                - appdev
                maxapplications: 20
            queues:
              - name: level2-2
                limits:
                  - limit:
                    users:
                    - user@domain
                    maxapplications: 1
              - name: level2-2
                limits:
                  - limit:
                    users:
                    - user@domain
                    maxapplications: 50